version: '3.7'
services:
    mongodb-Cont:
      image: mongo:latest 
      container_name: mongoDB-Cont 
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_cont:/data/db
    nest-Cont:
      image: nest-cloud-run
      container_name: nest-Cont
      ports:
        - 3000:3000
      depends_on:
        - mongodb-Cont

volumes:
  mongodb_data_cont: